### ISSUE TITLE
Use of dataset?

### ISSUE THREAD

**Issue by Maddocent** [uashogeschoolutrecht/tmoi-ml-19#1]
Dear Raoul,

I saw your commit and the dataset `cancer` you are using. May I ask, can I use it for the Data Mining course as well? Would be great to let the students also practice with classical statistical approaches such as multiple regression and mixed models.

May I ask what the source is of this dataset: Kaggle perhaps?

Cheers,
Marc

**Comment by raoulg** [comment]
Sure! The dataset, I'm not sure how we got that, tbh.
I'm quite sure it is this one, though: https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29
